### ISSUE TITLE
.sh documents

### ISSUE THREAD

**Issue by yunjuyan** [xssstory/SeqCo#1]
[Hi! Can you provide the following documents]()：
sh seqco_scripts/bpe_preprocess.sh
sh binarize.sh
sh seqco_scripts/train_cnndm.sh
sh seqco_scripts/infer_cnndm.sh
sh seqco_script/evaluate_sum.sh $PATH_TO_GENERATED_SUMMAY $CHECKPOINT

**Comment by xssstory** [comment]
I am sorry that *.sh appears in .gitignore. 
Scripts are uploaded now.  : )

**Comment by yunjuyan** [comment]
已收到
